# Site Settings
title:               Romain Vincent
tagline:             
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "http://rmnvncnt.github.io"
author:
  name:              "Romain Vincent"
  email:             "rmnvncnt@gmail.com"
  twitter:           ""
  instagram:         ""
  github:            "rmnvncnt"
  facebook:          ""
  linkedin:          "romain20100"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
